name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get variables
        id: get_vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "DATE=$(date +'%D')" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Bump package version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version ${{ github.ref_name }} --git-tag-version false

      - name: Run build
        run: bun run build

      - name: Update repository
        run: |
          git add .
          git commit -am '${{ github.ref_name }}'
          git push

      - name: Bundle files
        run: |
          zip -r ${{ github.event.repository.name }}.zip . -x "./.*" "./node_modules/*" "./scripts/*" "./src/*" "./web/*" "./tsconfig.json" "./bun.lock" "./package.json" "./biome.json"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
